// GENERATED by scripts/bundle-advisories.mjs from /advisories — do not edit by hand.
import { McpaAdvisory } from './types.js';

export const MCPA_ADVISORIES: McpaAdvisory[] = [
  {
    "id": "MCPA-2025-0001",
    "title": "mcp-remote OS command injection via untrusted MCP server (CVE-2025-6514)",
    "type": "rce-vectors",
    "severity": "critical",
    "published": "2025-07-09",
    "packages": [
      {
        "ecosystem": "npm",
        "name": "mcp-remote",
        "ranges": [
          {
            "introduced": "0.0.5",
            "fixed": "0.1.16"
          }
        ]
      }
    ]
  },
  {
    "id": "MCPA-2025-0002",
    "title": "postmark-mcp npm package backdoored to exfiltrate emails via hidden BCC",
    "type": "malicious-package",
    "severity": "critical",
    "published": "2025-09-25",
    "packages": [
      {
        "ecosystem": "npm",
        "name": "postmark-mcp",
        "ranges": [
          {
            "introduced": "1.0.16",
            "last_affected": "1.0.18"
          }
        ]
      }
    ]
  },
  {
    "id": "MCPA-2025-0003",
    "title": "MCP Inspector proxy allows unauthenticated remote code execution (CVE-2025-49596)",
    "type": "auth-missing",
    "severity": "critical",
    "published": "2025-06-13",
    "packages": [
      {
        "ecosystem": "npm",
        "name": "@modelcontextprotocol/inspector",
        "ranges": [
          {
            "introduced": "0.0.0",
            "fixed": "0.14.1"
          }
        ]
      }
    ]
  },
  {
    "id": "MCPA-2025-0004",
    "title": "@modelcontextprotocol/server-filesystem path validation bypass via colliding path prefix (CVE-2025-53110)",
    "type": "path-traversal",
    "severity": "high",
    "published": "2025-07-01",
    "packages": [
      {
        "ecosystem": "npm",
        "name": "@modelcontextprotocol/server-filesystem",
        "ranges": [
          {
            "introduced": "0.0.0",
            "last_affected": "0.6.2"
          },
          {
            "introduced": "2025.1.14",
            "fixed": "2025.7.1"
          }
        ]
      }
    ]
  },
  {
    "id": "MCPA-2025-0005",
    "title": "@modelcontextprotocol/server-filesystem symlink bypass enables full filesystem access (CVE-2025-53109)",
    "type": "path-traversal",
    "severity": "high",
    "published": "2025-07-02",
    "packages": [
      {
        "ecosystem": "npm",
        "name": "@modelcontextprotocol/server-filesystem",
        "ranges": [
          {
            "introduced": "0.0.0",
            "fixed": "0.6.4"
          },
          {
            "introduced": "2025.1.14",
            "fixed": "2025.7.1"
          }
        ]
      }
    ]
  },
  {
    "id": "MCPA-2025-0006",
    "title": "@cyanheads/git-mcp-server command injection in several git tools (CVE-2025-53107)",
    "type": "rce-vectors",
    "severity": "high",
    "published": "2025-06-29",
    "packages": [
      {
        "ecosystem": "npm",
        "name": "@cyanheads/git-mcp-server",
        "ranges": [
          {
            "introduced": "0",
            "fixed": "2.1.5"
          }
        ]
      }
    ]
  },
  {
    "id": "MCPA-2025-0007",
    "title": "mcp-server-kubernetes command injection in several kubectl tools (CVE-2025-53355)",
    "type": "rce-vectors",
    "severity": "high",
    "published": "2025-07-08",
    "packages": [
      {
        "ecosystem": "npm",
        "name": "mcp-server-kubernetes",
        "ranges": [
          {
            "introduced": "0",
            "fixed": "2.5.0"
          }
        ]
      }
    ]
  },
  {
    "id": "MCPA-2025-0008",
    "title": "mcp-package-docs command injection in several tools (CVE-2025-54073)",
    "type": "rce-vectors",
    "severity": "high",
    "published": "2025-07-18",
    "packages": [
      {
        "ecosystem": "npm",
        "name": "mcp-package-docs",
        "ranges": [
          {
            "introduced": "0",
            "fixed": "0.1.28"
          }
        ]
      }
    ]
  },
  {
    "id": "MCPA-2025-0009",
    "title": "@akoskm/create-mcp-server-stdio command injection via exec in which-app-on-port tool (CVE-2025-54994)",
    "type": "rce-vectors",
    "severity": "critical",
    "published": "2025-09-08",
    "packages": [
      {
        "ecosystem": "npm",
        "name": "@akoskm/create-mcp-server-stdio",
        "ranges": [
          {
            "introduced": "0",
            "fixed": "0.0.13"
          }
        ]
      }
    ]
  },
  {
    "id": "MCPA-2025-0010",
    "title": "adb-mcp command injection in inspect_ui tool (CVE-2025-59834)",
    "type": "rce-vectors",
    "severity": "critical",
    "published": "2025-09-24",
    "packages": [
      {
        "ecosystem": "npm",
        "name": "adb-mcp",
        "ranges": [
          {
            "introduced": "0",
            "last_affected": "0.1.0"
          }
        ]
      }
    ]
  },
  {
    "id": "MCPA-2025-0011",
    "title": "figma-developer-mcp (Framelink Figma MCP) command injection in get_figma_data (CVE-2025-53967)",
    "type": "rce-vectors",
    "severity": "high",
    "published": "2025-09-29",
    "packages": [
      {
        "ecosystem": "npm",
        "name": "figma-developer-mcp",
        "ranges": [
          {
            "introduced": "0",
            "fixed": "0.6.3"
          }
        ]
      }
    ]
  },
  {
    "id": "MCPA-2025-0012",
    "title": "@lanyer640/mcp-runcommand-server npm package backdoored with dual reverse shells",
    "type": "malicious-package",
    "severity": "critical",
    "published": "2025-10-02",
    "packages": [
      {
        "ecosystem": "npm",
        "name": "@lanyer640/mcp-runcommand-server",
        "ranges": [
          {
            "introduced": "1.0.6"
          }
        ]
      }
    ]
  },
  {
    "id": "MCPA-2025-0013",
    "title": "mcp-fetch-server SSRF via private-IP validation bypass (CVE-2025-65513)",
    "type": "ssrf",
    "severity": "medium",
    "published": "2025-12-09",
    "packages": [
      {
        "ecosystem": "npm",
        "name": "mcp-fetch-server",
        "ranges": [
          {
            "introduced": "0",
            "last_affected": "1.0.2"
          }
        ]
      }
    ]
  },
  {
    "id": "MCPA-2025-0014",
    "title": "Malicious npm package mcp-server-everything squats the MCP reference \"everything\" server",
    "type": "malicious-package",
    "severity": "critical",
    "published": "2025-09-09",
    "packages": [
      {
        "ecosystem": "npm",
        "name": "mcp-server-everything",
        "ranges": [
          {
            "introduced": "0"
          }
        ]
      }
    ]
  },
  {
    "id": "MCPA-2026-0001",
    "title": "Azure MCP Server server-side request forgery allows privilege elevation (CVE-2026-26118)",
    "type": "ssrf",
    "severity": "high",
    "published": "2026-03-10",
    "packages": [
      {
        "ecosystem": "npm",
        "name": "@azure/mcp",
        "ranges": [
          {
            "introduced": "1.0.0",
            "fixed": "1.0.2"
          },
          {
            "introduced": "2.0.0-beta.1",
            "fixed": "2.0.0-beta.17"
          }
        ]
      },
      {
        "ecosystem": "nuget",
        "name": "Azure.Mcp",
        "ranges": [
          {
            "introduced": "1.0.0",
            "fixed": "1.0.2"
          },
          {
            "introduced": "2.0.0-beta.1",
            "fixed": "2.0.0-beta.17"
          }
        ]
      },
      {
        "ecosystem": "pypi",
        "name": "msmcp-azure",
        "ranges": [
          {
            "introduced": "2.0.0b14",
            "fixed": "2.0.0b17"
          }
        ]
      }
    ]
  },
  {
    "id": "MCPA-2026-0002",
    "title": "n8n-mcp path traversal, redirect-following SSRF, and telemetry payload exposure",
    "type": "ssrf",
    "severity": "high",
    "published": "2026-05-04",
    "packages": [
      {
        "ecosystem": "npm",
        "name": "n8n-mcp",
        "ranges": [
          {
            "introduced": "0",
            "fixed": "2.50.1"
          }
        ]
      }
    ]
  },
  {
    "id": "MCPA-2026-0003",
    "title": "explorhub-mcp-server is a malicious npm package",
    "type": "malicious-package",
    "severity": "critical",
    "published": "2026-05-25",
    "packages": [
      {
        "ecosystem": "npm",
        "name": "explorhub-mcp-server",
        "ranges": [
          {
            "introduced": "0"
          }
        ]
      }
    ]
  },
  {
    "id": "MCPA-2026-0004",
    "title": "ray-mcp-server 0.2.1 shipped malicious code (Hades/Shai-Hulud PyPI campaign)",
    "type": "malicious-package",
    "severity": "critical",
    "published": "2026-07-07",
    "packages": [
      {
        "ecosystem": "pypi",
        "name": "ray-mcp-server",
        "ranges": [
          {
            "introduced": "0.2.1",
            "last_affected": "0.2.1"
          }
        ]
      }
    ]
  },
  {
    "id": "MCPA-2026-0005",
    "title": "mcp-search-server (PyPI) is a malicious package",
    "type": "malicious-package",
    "severity": "critical",
    "published": "2026-07-30",
    "packages": [
      {
        "ecosystem": "pypi",
        "name": "mcp-search-server",
        "ranges": [
          {
            "introduced": "0"
          }
        ]
      }
    ]
  },
  {
    "id": "MCPA-2026-0006",
    "title": "Flowise MCP environment-variable blocklist bypass via npm_config_yes (unauthenticated RCE, CVE-2026-69263)",
    "type": "rce-vectors",
    "severity": "high",
    "published": "2026-08-04",
    "packages": [
      {
        "ecosystem": "npm",
        "name": "flowise",
        "ranges": [
          {
            "introduced": "0",
            "fixed": "3.1.3"
          }
        ]
      },
      {
        "ecosystem": "npm",
        "name": "flowise-components",
        "ranges": [
          {
            "introduced": "0",
            "fixed": "3.1.3"
          }
        ]
      }
    ]
  },
  {
    "id": "MCPA-2026-0007",
    "title": "gemini-bridge arbitrary local file read via consult_gemini_with_files inline mode (CVE-2026-54785)",
    "type": "path-traversal",
    "severity": "medium",
    "published": "2026-07-31",
    "packages": [
      {
        "ecosystem": "pypi",
        "name": "gemini-bridge",
        "ranges": [
          {
            "introduced": "1.0.0",
            "fixed": "1.3.1"
          }
        ]
      }
    ]
  },
  {
    "id": "MCPA-2026-0008",
    "title": "Flyto2 Core arbitrary file write via image.download output_dir bypass (CVE-2026-67429)",
    "type": "path-traversal",
    "severity": "critical",
    "published": "2026-07-30",
    "packages": [
      {
        "ecosystem": "pypi",
        "name": "flyto-core",
        "ranges": [
          {
            "introduced": "0",
            "fixed": "2.26.7"
          }
        ]
      }
    ]
  },
  {
    "id": "MCPA-2026-0009",
    "title": "Malicious npm packages squatting official MCP reference server names (mcp-server-fetch et al.)",
    "type": "malicious-package",
    "severity": "critical",
    "published": "2026-06-09",
    "packages": [
      {
        "ecosystem": "npm",
        "name": "mcp-server-fetch",
        "ranges": [
          {
            "introduced": "0"
          }
        ]
      },
      {
        "ecosystem": "npm",
        "name": "mcp-server-figma",
        "ranges": [
          {
            "introduced": "0"
          }
        ]
      },
      {
        "ecosystem": "npm",
        "name": "mcp-server-git",
        "ranges": [
          {
            "introduced": "0"
          }
        ]
      },
      {
        "ecosystem": "npm",
        "name": "mcp-server-github",
        "ranges": [
          {
            "introduced": "0"
          }
        ]
      },
      {
        "ecosystem": "npm",
        "name": "mcp-server-notion",
        "ranges": [
          {
            "introduced": "0"
          }
        ]
      },
      {
        "ecosystem": "npm",
        "name": "mcp-server-postgres",
        "ranges": [
          {
            "introduced": "0"
          }
        ]
      },
      {
        "ecosystem": "npm",
        "name": "mcp-server-redis",
        "ranges": [
          {
            "introduced": "0"
          }
        ]
      },
      {
        "ecosystem": "npm",
        "name": "mcp-server-sentry",
        "ranges": [
          {
            "introduced": "0"
          }
        ]
      },
      {
        "ecosystem": "npm",
        "name": "mcp-server-sequential-thinking",
        "ranges": [
          {
            "introduced": "0"
          }
        ]
      },
      {
        "ecosystem": "npm",
        "name": "mcp-server-supabase",
        "ranges": [
          {
            "introduced": "0"
          }
        ]
      }
    ]
  },
  {
    "id": "MCPA-2026-0010",
    "title": "Malicious PyPI packages impersonating popular AI libraries as MCP servers (openai-mcp, langchain-core-mcp, tiktoken-mcp, instructor-mcp)",
    "type": "malicious-package",
    "severity": "critical",
    "published": "2026-06-08",
    "packages": [
      {
        "ecosystem": "pypi",
        "name": "openai-mcp",
        "ranges": [
          {
            "introduced": "0"
          }
        ]
      },
      {
        "ecosystem": "pypi",
        "name": "langchain-core-mcp",
        "ranges": [
          {
            "introduced": "0"
          }
        ]
      },
      {
        "ecosystem": "pypi",
        "name": "tiktoken-mcp",
        "ranges": [
          {
            "introduced": "0"
          }
        ]
      },
      {
        "ecosystem": "pypi",
        "name": "instructor-mcp",
        "ranges": [
          {
            "introduced": "0"
          }
        ]
      }
    ]
  },
  {
    "id": "MCPA-2026-0011",
    "title": "AWS Labs DocumentDB MCP Server read-only mode bypass via write-capable aggregation pipeline stages (CVE-2026-18954)",
    "type": "auth-missing",
    "severity": "medium",
    "published": "2026-08-05",
    "packages": [
      {
        "ecosystem": "pypi",
        "name": "awslabs.documentdb-mcp-server",
        "ranges": [
          {
            "introduced": "0",
            "fixed": "1.0.12"
          }
        ]
      }
    ]
  },
  {
    "id": "MCPA-2026-0012",
    "title": "Flyto2 Core unauthenticated command execution via HTTP MCP execute_module (CVE-2026-55786)",
    "type": "rce-vectors",
    "severity": "high",
    "published": "2026-07-06",
    "packages": [
      {
        "ecosystem": "pypi",
        "name": "flyto-core",
        "ranges": [
          {
            "introduced": "2.26.2",
            "fixed": "2.26.4"
          }
        ]
      }
    ]
  },
  {
    "id": "MCPA-2026-0013",
    "title": "Flyto2 Core SSRF guard bypass via IPv6 transition addresses (CVE-2026-55787)",
    "type": "ssrf",
    "severity": "high",
    "published": "2026-07-06",
    "packages": [
      {
        "ecosystem": "pypi",
        "name": "flyto-core",
        "ranges": [
          {
            "introduced": "0",
            "fixed": "2.26.3"
          }
        ]
      }
    ]
  },
  {
    "id": "MCPA-2026-0014",
    "title": "Flyto2 Core 2026-07-30 batch: unauthenticated callback SSRF, secret leaks, and guard bypasses (CVE-2026-67424..67428)",
    "type": "ssrf",
    "severity": "critical",
    "published": "2026-07-30",
    "packages": [
      {
        "ecosystem": "pypi",
        "name": "flyto-core",
        "ranges": [
          {
            "introduced": "0",
            "fixed": "2.26.7"
          }
        ]
      }
    ]
  },
  {
    "id": "MCPA-2026-0015",
    "title": "LudusMCP get_credential_from_user command injection via secret-dialog description (CVE-2026-19045)",
    "type": "rce-vectors",
    "severity": "medium",
    "published": "2026-08-06",
    "packages": [
      {
        "ecosystem": "npm",
        "name": "ludus-mcp",
        "ranges": [
          {
            "introduced": "0",
            "last_affected": "1.0.24"
          }
        ]
      }
    ]
  },
  {
    "id": "MCPA-2026-0016",
    "title": "LudusMCP ludus_cli_execute command injection via command/args arguments (CVE-2026-19047)",
    "type": "rce-vectors",
    "severity": "medium",
    "published": "2026-08-06",
    "packages": [
      {
        "ecosystem": "npm",
        "name": "ludus-mcp",
        "ranges": [
          {
            "introduced": "0",
            "last_affected": "1.0.24"
          }
        ]
      }
    ]
  },
  {
    "id": "MCPA-2026-0017",
    "title": "LudusMCP ludus_environment_guides_search path traversal via guide_name (CVE-2026-19046)",
    "type": "path-traversal",
    "severity": "low",
    "published": "2026-08-06",
    "packages": [
      {
        "ecosystem": "npm",
        "name": "ludus-mcp",
        "ranges": [
          {
            "introduced": "0",
            "last_affected": "1.0.24"
          }
        ]
      }
    ]
  },
  {
    "id": "MCPA-2026-0018",
    "title": "n8n-MCP cross-tenant access to workflow version backups in multi-tenant HTTP deployments (CVE-2026-54052)",
    "type": "credential-leak",
    "severity": "critical",
    "published": "2026-07-14",
    "packages": [
      {
        "ecosystem": "npm",
        "name": "n8n-mcp",
        "ranges": [
          {
            "introduced": "0",
            "fixed": "2.56.1"
          }
        ]
      }
    ]
  },
  {
    "id": "MCPA-2026-0019",
    "title": "n8n-MCP incorrect authorization exposes default-scope workflow version backups in multi-tenant HTTP mode (CVE-2026-55608)",
    "type": "credential-leak",
    "severity": "medium",
    "published": "2026-07-14",
    "packages": [
      {
        "ecosystem": "npm",
        "name": "n8n-mcp",
        "ranges": [
          {
            "introduced": "0",
            "fixed": "2.57.4"
          }
        ]
      }
    ]
  },
  {
    "id": "MCPA-2026-0020",
    "title": "HKUDS nanobot improper access controls in MCP enabledTools scope handler (CVE-2026-19244)",
    "type": "overprivileged",
    "severity": "low",
    "published": "2026-08-07",
    "packages": [
      {
        "ecosystem": "pypi",
        "name": "nanobot-ai",
        "ranges": [
          {
            "introduced": "0",
            "fixed": "0.3.0"
          }
        ]
      }
    ]
  },
  {
    "id": "MCPA-2026-0021",
    "title": "HKUDS nanobot SSRF in the web_fetch tool via 3xx redirects (CVE-2026-49138)",
    "type": "ssrf",
    "severity": "medium",
    "published": "2026-06-01",
    "packages": [
      {
        "ecosystem": "pypi",
        "name": "nanobot-ai",
        "ranges": [
          {
            "introduced": "0",
            "fixed": "0.2.1"
          }
        ]
      }
    ]
  }
];
