// GENERATED by scripts/bundle-advisories.mjs from /advisories — do not edit by hand.
import { McpaAdvisory } from './types.js';

export const MCPA_ADVISORIES: McpaAdvisory[] = [
  {
    "id": "MCPA-2025-0001",
    "title": "mcp-remote OS command injection via untrusted MCP server (CVE-2025-6514)",
    "type": "rce-vectors",
    "severity": "critical",
    "packages": [
      {
        "ecosystem": "npm",
        "name": "mcp-remote",
        "ranges": [
          {
            "introduced": "0.0.5",
            "fixed": "0.1.16"
          }
        ]
      }
    ]
  },
  {
    "id": "MCPA-2025-0002",
    "title": "postmark-mcp npm package backdoored to exfiltrate emails via hidden BCC",
    "type": "malicious-package",
    "severity": "critical",
    "packages": [
      {
        "ecosystem": "npm",
        "name": "postmark-mcp",
        "ranges": [
          {
            "introduced": "1.0.16",
            "last_affected": "1.0.18"
          }
        ]
      }
    ]
  },
  {
    "id": "MCPA-2025-0003",
    "title": "MCP Inspector proxy allows unauthenticated remote code execution (CVE-2025-49596)",
    "type": "auth-missing",
    "severity": "critical",
    "packages": [
      {
        "ecosystem": "npm",
        "name": "@modelcontextprotocol/inspector",
        "ranges": [
          {
            "introduced": "0.0.0",
            "fixed": "0.14.1"
          }
        ]
      }
    ]
  },
  {
    "id": "MCPA-2025-0004",
    "title": "@modelcontextprotocol/server-filesystem path validation bypass via colliding path prefix (CVE-2025-53110)",
    "type": "path-traversal",
    "severity": "high",
    "packages": [
      {
        "ecosystem": "npm",
        "name": "@modelcontextprotocol/server-filesystem",
        "ranges": [
          {
            "introduced": "0.0.0",
            "last_affected": "0.6.2"
          },
          {
            "introduced": "2025.1.14",
            "fixed": "2025.7.1"
          }
        ]
      }
    ]
  },
  {
    "id": "MCPA-2025-0005",
    "title": "@modelcontextprotocol/server-filesystem symlink bypass enables full filesystem access (CVE-2025-53109)",
    "type": "path-traversal",
    "severity": "high",
    "packages": [
      {
        "ecosystem": "npm",
        "name": "@modelcontextprotocol/server-filesystem",
        "ranges": [
          {
            "introduced": "0.0.0",
            "fixed": "0.6.4"
          },
          {
            "introduced": "2025.1.14",
            "fixed": "2025.7.1"
          }
        ]
      }
    ]
  },
  {
    "id": "MCPA-2025-0006",
    "title": "@cyanheads/git-mcp-server command injection in several git tools (CVE-2025-53107)",
    "type": "rce-vectors",
    "severity": "high",
    "packages": [
      {
        "ecosystem": "npm",
        "name": "@cyanheads/git-mcp-server",
        "ranges": [
          {
            "introduced": "0",
            "fixed": "2.1.5"
          }
        ]
      }
    ]
  },
  {
    "id": "MCPA-2025-0007",
    "title": "mcp-server-kubernetes command injection in several kubectl tools (CVE-2025-53355)",
    "type": "rce-vectors",
    "severity": "high",
    "packages": [
      {
        "ecosystem": "npm",
        "name": "mcp-server-kubernetes",
        "ranges": [
          {
            "introduced": "0",
            "fixed": "2.5.0"
          }
        ]
      }
    ]
  },
  {
    "id": "MCPA-2025-0008",
    "title": "mcp-package-docs command injection in several tools (CVE-2025-54073)",
    "type": "rce-vectors",
    "severity": "high",
    "packages": [
      {
        "ecosystem": "npm",
        "name": "mcp-package-docs",
        "ranges": [
          {
            "introduced": "0",
            "fixed": "0.1.28"
          }
        ]
      }
    ]
  },
  {
    "id": "MCPA-2025-0009",
    "title": "@akoskm/create-mcp-server-stdio command injection via exec in which-app-on-port tool (CVE-2025-54994)",
    "type": "rce-vectors",
    "severity": "critical",
    "packages": [
      {
        "ecosystem": "npm",
        "name": "@akoskm/create-mcp-server-stdio",
        "ranges": [
          {
            "introduced": "0",
            "fixed": "0.0.13"
          }
        ]
      }
    ]
  },
  {
    "id": "MCPA-2025-0010",
    "title": "adb-mcp command injection in inspect_ui tool (CVE-2025-59834)",
    "type": "rce-vectors",
    "severity": "critical",
    "packages": [
      {
        "ecosystem": "npm",
        "name": "adb-mcp",
        "ranges": [
          {
            "introduced": "0",
            "last_affected": "0.1.0"
          }
        ]
      }
    ]
  },
  {
    "id": "MCPA-2025-0011",
    "title": "figma-developer-mcp (Framelink Figma MCP) command injection in get_figma_data (CVE-2025-53967)",
    "type": "rce-vectors",
    "severity": "high",
    "packages": [
      {
        "ecosystem": "npm",
        "name": "figma-developer-mcp",
        "ranges": [
          {
            "introduced": "0",
            "fixed": "0.6.3"
          }
        ]
      }
    ]
  },
  {
    "id": "MCPA-2025-0012",
    "title": "@lanyer640/mcp-runcommand-server npm package backdoored with dual reverse shells",
    "type": "malicious-package",
    "severity": "critical",
    "packages": [
      {
        "ecosystem": "npm",
        "name": "@lanyer640/mcp-runcommand-server",
        "ranges": [
          {
            "introduced": "1.0.6"
          }
        ]
      }
    ]
  },
  {
    "id": "MCPA-2025-0013",
    "title": "mcp-fetch-server SSRF via private-IP validation bypass (CVE-2025-65513)",
    "type": "ssrf",
    "severity": "medium",
    "packages": [
      {
        "ecosystem": "npm",
        "name": "mcp-fetch-server",
        "ranges": [
          {
            "introduced": "0",
            "last_affected": "1.0.2"
          }
        ]
      }
    ]
  },
  {
    "id": "MCPA-2026-0001",
    "title": "Azure MCP Server server-side request forgery allows privilege elevation (CVE-2026-26118)",
    "type": "ssrf",
    "severity": "high",
    "packages": [
      {
        "ecosystem": "npm",
        "name": "@azure/mcp",
        "ranges": [
          {
            "introduced": "1.0.0",
            "fixed": "1.0.2"
          },
          {
            "introduced": "2.0.0-beta.1",
            "fixed": "2.0.0-beta.17"
          }
        ]
      },
      {
        "ecosystem": "nuget",
        "name": "Azure.Mcp",
        "ranges": [
          {
            "introduced": "1.0.0",
            "fixed": "1.0.2"
          },
          {
            "introduced": "2.0.0-beta.1",
            "fixed": "2.0.0-beta.17"
          }
        ]
      },
      {
        "ecosystem": "pypi",
        "name": "msmcp-azure",
        "ranges": [
          {
            "introduced": "2.0.0b14",
            "fixed": "2.0.0b17"
          }
        ]
      }
    ]
  },
  {
    "id": "MCPA-2026-0002",
    "title": "n8n-mcp path traversal, redirect-following SSRF, and telemetry payload exposure",
    "type": "ssrf",
    "severity": "high",
    "packages": [
      {
        "ecosystem": "npm",
        "name": "n8n-mcp",
        "ranges": [
          {
            "introduced": "0",
            "fixed": "2.50.1"
          }
        ]
      }
    ]
  },
  {
    "id": "MCPA-2026-0003",
    "title": "explorhub-mcp-server is a malicious npm package",
    "type": "malicious-package",
    "severity": "critical",
    "packages": [
      {
        "ecosystem": "npm",
        "name": "explorhub-mcp-server",
        "ranges": [
          {
            "introduced": "0"
          }
        ]
      }
    ]
  },
  {
    "id": "MCPA-2026-0004",
    "title": "ray-mcp-server 0.2.1 shipped malicious code (Hades/Shai-Hulud PyPI campaign)",
    "type": "malicious-package",
    "severity": "critical",
    "packages": [
      {
        "ecosystem": "pypi",
        "name": "ray-mcp-server",
        "ranges": [
          {
            "introduced": "0.2.1",
            "last_affected": "0.2.1"
          }
        ]
      }
    ]
  },
  {
    "id": "MCPA-2026-0005",
    "title": "mcp-search-server (PyPI) is a malicious package",
    "type": "malicious-package",
    "severity": "critical",
    "packages": [
      {
        "ecosystem": "pypi",
        "name": "mcp-search-server",
        "ranges": [
          {
            "introduced": "0"
          }
        ]
      }
    ]
  },
  {
    "id": "MCPA-2026-0006",
    "title": "Flowise MCP environment-variable blocklist bypass via npm_config_yes (unauthenticated RCE, CVE-2026-69263)",
    "type": "rce-vectors",
    "severity": "high",
    "packages": [
      {
        "ecosystem": "npm",
        "name": "flowise",
        "ranges": [
          {
            "introduced": "0",
            "fixed": "3.1.3"
          }
        ]
      },
      {
        "ecosystem": "npm",
        "name": "flowise-components",
        "ranges": [
          {
            "introduced": "0",
            "fixed": "3.1.3"
          }
        ]
      }
    ]
  },
  {
    "id": "MCPA-2026-0007",
    "title": "gemini-bridge arbitrary local file read via consult_gemini_with_files inline mode (CVE-2026-54785)",
    "type": "path-traversal",
    "severity": "medium",
    "packages": [
      {
        "ecosystem": "pypi",
        "name": "gemini-bridge",
        "ranges": [
          {
            "introduced": "1.0.0",
            "fixed": "1.3.1"
          }
        ]
      }
    ]
  },
  {
    "id": "MCPA-2026-0008",
    "title": "Flyto2 Core arbitrary file write via image.download output_dir bypass (CVE-2026-67429)",
    "type": "path-traversal",
    "severity": "critical",
    "packages": [
      {
        "ecosystem": "pypi",
        "name": "flyto-core",
        "ranges": [
          {
            "introduced": "0",
            "fixed": "2.26.7"
          }
        ]
      }
    ]
  }
];
